basePath: /api/v1
definitions:
  models.User:
    properties:
      age:
        type: integer
      gender:
        type: string
      height:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: myProj后端api文档服务.
  title: myProj API
  version: "1.0"
paths:
  /addUser:
    post:
      consumes:
      - application/json
      description: 测试的接口
      parameters:
      - description: 新增的用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: example for add a user
      tags:
      - Test
  /deleteUser:
    delete:
      consumes:
      - application/json
      description: 测试的接口
      parameters:
      - default: 张三
        description: 用户名
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: example for delete a user
      tags:
      - Test
  /getUser:
    get:
      consumes:
      - application/json
      description: 测试的接口
      parameters:
      - description: 根據用戶名來查用戶
        in: query
        name: user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: example for get a user
      tags:
      - Test
  /updateUser:
    put:
      consumes:
      - application/json
      description: 测试的接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: example for update a user
      tags:
      - Test
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
